### ISSUE TITLE
Configure error - configure: error: cannot find zlib header 

### ISSUE THREAD

**Issue by floydpink** [dhvani-tts/dhvani-tts#2]
Trying to compile the source on a Mac, getting the error running `./configure`: `configure: error: cannot find zlib header`.

Here is the full console output for the `./configure` command - http://pastebin.com/gwVpHgP2

And here is the content of the `config.log` file - http://pastebin.com/ac39CvZr

**Comment by santhoshtr** [comment]
There is no dependency on zlib library. It was a mistake in the error message. What you missed is gsm library. libgsm-dev is the package in linux.

See 3f0c7aefdc9e5801c36e46da3265d0bfd5dc2e77
