### ISSUE TITLE
dhvani

### ISSUE THREAD

**Issue by ghost** [dhvani-tts/dhvani-tts#7]
inability to insert the conf file into to the etc folder and unable to edit the espeak to insert other languages.

**Comment by santhoshtr** [comment]
> inability to insert the conf file into to the etc folder and unable to edit the espeak to insert other languages.

What conf file? Dhvani does not have any conf file. What is the issue with espeak here? Dhvani has no relation with espeak.

**Comment by prasannatsm** [comment]
Closing.
