### ISSUE TITLE
Unable to save output speech to file

### ISSUE THREAD

**Issue by ghost** [dhvani-tts/dhvani-tts#8]
I had compiled dhvani using the --with-vorbis option. dhvani -t "some text" option works well but I am unable to save the output to a file using the option "-o".

I have used both format options, WAV and OGG but to no avail. 
dhvani -o temp.ogg -f OGG testMalayalamText.txt
dhvani -o temp.wav -f WAV testMalayalamText.txt

I have also tried unsuccessfully, without -f option. 

The terminal shows no errors.

Are there any clues to what could be wrong or where to look for troubleshooting this.

**Comment by prasannatsm** [comment]
I am able to reproduce this issue. Will look into this in some time.

**Comment by prasannatsm** [comment]
So far I did not get time to work on this issue. Can you please check if this was working in previous stable release? If so please try to find which change that caused this issue - you can use got bisect for this I guess.

Your inputs will help in improving Dhvani. Thanks in advance.

**Comment by ghost** [comment]
Thank you. I will try and let you know.

**Comment by ghost** [comment]
I verified that this works in dhvani-0.95 available in sourceforge. I'll try to find what change caused this issue.

**Comment by prasannatsm** [comment]
Checked this issue with dhvani-0.95 taken from sourceforge. Even though dhvani did not return any error, it is not creating any output file. I think the feature was not working during the 0.95 release. Closing this bug. If the feature _really_ works please feel free to reopen the bug.
